### ISSUE TITLE
python 需要多少版本以上？centos6.5安装出错

### ISSUE THREAD

**Issue by huaimutou** [inpanel/inpanel#32]
Traceback (most recent call last):
  File "install.py", line 392, in <module>
    install.install()
  File "install.py", line 369, in install
    self.config_account()
  File "install.py", line 272, in config_account
    self._run('%s/config.py username "%s"' % (self.installpath, self.username))
  File "install.py", line 111, in _run
    return subprocess.call(shlex.split(cmd))
  File "/usr/lib/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by doudoudzj** [comment]
2.7

**Comment by weizhiwen** [comment]
centos7 同意的错误

**Comment by jksdou** [comment]
@weizhiwen 建议参考这个文档 https://inpanel.org/zh-cn/install/custom.html ，手动安装
