### ISSUE TITLE
Debian11安装失败

### ISSUE THREAD

**Issue by HZDZ9495** [InPanel/inpanel#40]
使用安装脚本报错
* Config firewall... Starting InPanel [ FAILED ]
* ============================
*                          *
*     INSTALL COMPLETED    *
*                          *
============================

The URL of your InPanel is:
Traceback (most recent call last):
  File "install.py", line 392, in <module>
    install.install()
  File "install.py", line 381, in install
    print('\033[4;34mhttp://%s:%s/\033[0m' % (self.detect_ip(), self.listen_port))
  File "install.py", line 277, in detect_ip
    ip = request.urlopen('http://ip.42.pl/raw').readline()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1208, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1161, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

**Comment by jksdou** [comment]
@HZDZ9495 不支持 Debian ...
